Extend API interface for courses
LearningBay24/LearningBay24-backend pull request #28
Opened 2022-04-22 22:38 UTC by Schorzel

- Added GetCourse()
- Added GetUserCourses()
- Added DeleteUserFromCourse()

2022-04-26 15:09 UTC, Witcher01 commented on course/course.go
> +	courses, err := models.Courses(qm.SQL("SELECT * FROM learningbay24.user_has_course,learningbay24.course WHERE learningbay24.user_has_course.user_id = ? AND learningbay24.user_has_course.course_id =
Gibts da ne Möglichkeit das ohne Raw SQL mit sqlboiler zu lösen? Wäre sicherer

2022-04-26 15:09 UTC, Witcher01 commented on course/course.go
> +	users, err := models.Users(qm.SQL("SELECT * FROM learningbay24.user_has_course,learningbay24.user WHERE  learningbay24.user_has_course.course_id=? AND learningbay24.user_has_course.user_id = learnin
Hier genauso. Vielleicht ohne raw SQL?

2022-04-26 17:05 UTC, Schorzel commented on course/course.go
> +	courses, err := models.Courses(qm.SQL("SELECT * FROM learningbay24.user_has_course,learningbay24.course WHERE learningbay24.user_has_course.user_id = ? AND learningbay24.user_has_course.course_id =
Werd ich mal schauen

2022-04-28 17:01 UTC, Witcher01 requested changes
Passt. Bitte noch auf `main` rebasen, dann kann ich mit `main` mergen.
`git fetch origin main`, `git rebase origin/main`.

2022-04-29 15:14 UTC, Witcher01 requested changes
- Transaktionen rauslassen, wo sie nicht benötigt werden
- In den neuen `fmt.Errorf` die Errors mit `Error` zurückgeben lassen
- Rückgabewerte abändern, wenn es für sie keinen Grund gibt

2022-04-29 15:14 UTC, Witcher01 commented on course/course.go
> +func DeactivateCourse(db *sql.DB, id int) (*models.Course, error) {
Wofür wird der Kurs dann zurückgegeben? Den sollten wir eigentlich nicht mehr brauchen, wenn der deaktiviert ist.

2022-04-29 15:14 UTC, Witcher01 commented on course/course.go
> +func DeleteUserFromCourse(db *sql.DB, uid int, cid int) (*models.User, error) {
Hier auch die Frage, wofür man den Nutzer zurückgeben muss 🤔

2022-04-29 15:14 UTC, Witcher01 commented on course/course.go
> +	_, err = f.Update(context.Background(), tx, boil.Infer())
Mit einem `Delete` sollte es schon
https://github.com/volatiletech/sqlboiler/#automatic-deletedat-soft-delete

2022-04-29 15:14 UTC, Witcher01 commented on course/course.go
> +	_, err = f.Delete(context.Background(), tx, true)
`Delete` löscht nicht den Eintrag, weil wir Soft Delete benutzen.
https://github.com/volatiletech/sqlboiler/#automatic-deletedat-soft-delete
Kannst du, wenn du keinen anderen Weg findest, mit einem Raw SQL Statement löschen.

2022-04-29 15:14 UTC, Witcher01 commented on course/course.go
> +		if e := tx.Rollback(); e != nil {
Bei einem Find brauchen wir noch keine Transaction - du kannst dir also das Rollback sparen und oben bei `models.FindUserHasCourse` `db` benutzen

2022-04-29 15:14 UTC, Witcher01 commented on course/course.go
> +		if e := tx.Rollback(); e != nil {
Hier genauso, du änderst die Datenbank nicht sondern rufst nur ab. Die Transaktion kannst du lassen und dir das `Rollback` sparen.

2022-04-29 15:14 UTC, Witcher01 commented on course/course.go
> +	c, err := models.FindCourse(context.Background(), tx, cid)
Hier auch wieder, keine Änderung an der Datenbank, also keine Transaktion notwendig.

2022-05-06 15:28 UTC, merged